//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("msac_competition.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будьте уважніше!.
        /// </summary>
        public static string beAttentive {
            get {
                return ResourceManager.GetString("beAttentive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityService can&apos;t be null.
        /// </summary>
        public static string cityServiceNullException {
            get {
                return ResourceManager.GetString("cityServiceNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoachService can&apos;t be null.
        /// </summary>
        public static string coachServiceNullException {
            get {
                return ResourceManager.GetString("coachServiceNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompetitionService can&apos;t be null.
        /// </summary>
        public static string competitionServiceNullException {
            get {
                return ResourceManager.GetString("competitionServiceNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сталася помилка!.
        /// </summary>
        public static string errorHappened {
            get {
                return ResourceManager.GetString("errorHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сталася помилка під час виконання операції!.
        /// </summary>
        public static string errorHappenedDuringRequest {
            get {
                return ResourceManager.GetString("errorHappenedDuringRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FstService can&apos;t be null.
        /// </summary>
        public static string fstServiceNullException {
            get {
                return ResourceManager.GetString("fstServiceNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapper can&apos;t be null.
        /// </summary>
        public static string mapper {
            get {
                return ResourceManager.GetString("mapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SportmanService can&apos;t be null.
        /// </summary>
        public static string sportmanServiceNullException {
            get {
                return ResourceManager.GetString("sportmanServiceNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamService can&apos;t be null.
        /// </summary>
        public static string teamServiceNullException {
            get {
                return ResourceManager.GetString("teamServiceNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спробуйте ще раз!.
        /// </summary>
        public static string tryAgain {
            get {
                return ResourceManager.GetString("tryAgain", resourceCulture);
            }
        }
    }
}
